# This is a basic workflow to help you get started with Actions

name: build-on-win

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ release ]
#   pull_request:
#     branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
      
    # Runs a single command using the runners shell
    - name: Install Dependencies
      run: yarn

    # Runs a set of commands using the runners shell
    - name: Start building
      run: yarn build 
    
    - name: make dir
      run: md -Name ./dist/artifacts -Force
    
    - uses: edgarrc/action-7zip@v1.0.4
      with:
        args: 7z a -ttar -mx=9 ./dist/artifacts/windows-unpacked.tar ./dist/win-unpacked
    
    - name: move artifacts
      run: Copy-Item ./dist/*.exe -Destination ./dist/artifacts
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: champ-r-installer
        # Directory containing files to upload
        path: "./dist/artifacts"
