name: ðŸ¶ Release Build

on:
  push:
    tags:
    - 'v*'

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - uses: pnpm/action-setup@v2.2.2
      with:
        version: 'latest'

    - name: Build & release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: pwsh
      run: |
        $sha = (git rev-parse --short HEAD)
        echo 'node-linker=hoisted' > .npmrc # make it work with electron
        pnpm i --frozen-lockfile
        $env:SHORT_SHA=$sha; pnpm run release

    - name: Move artifacts
      id: vars
      shell: pwsh
      run: |
        $sha = (git rev-parse --short HEAD)
        md -Name ./dist/artifacts -Force
        Copy-Item ./dist/*.exe -Destination ./dist/artifacts/
        $file = Get-ChildItem -Path ./dist/artifacts/ -Filter "*.exe" | select-object -first 1
        $newName = "$($file.BaseName).$($sha)$($file.Extension)"
        Rename-Item -Path $file.FullName -NewName $newName
        echo "::set-output name=fileName::$($newName)"

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: "./dist/artifacts/*"
        body: "[FAQ](https://github.com/cangzhang/champ-r/wiki/FAQ)\n[CHNAGELOG](https://github.com/cangzhang/champ-r/blob/main/CHANGELOG.md)"

#    - name: Upload artifacts
#      uses: actions/upload-artifact@v1.0.0
#      with:
#        name: ChampR-installer
#        path: "./dist/artifacts"
