name: ðŸ˜¼ Test Build

on:
  push:
    branches:
      - main
      - build
  pull_request:
    branches:
      - main

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - uses: pnpm/action-setup@v2.2.2
      with:
        version: 'latest'

    - name: Build
      env:
        GH_TOKEN: ${{ secrets.GH_DOWNLOAD_TOKEN }}
      run: |
        $release_name=(gh api -H "Accept: application/vnd.github+json" /repos/cangzhang/league-client-tencent/releases/latest --jq ".name")
        gh release download "$release_name" -R cangzhang/league-client-tencent -p "*exe" -D bin --clobber
        echo "ðŸ³ Downloaded LeagueClient $release_name"
        $sha = (git rev-parse --short HEAD)
        echo 'node-linker=hoisted' > .npmrc # make it work with electron
        pnpm i --frozen-lockfile
        $env:SHORT_SHA=$sha; pnpm run build:ci

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        path: |
          dist/win-unpacked/
#          dist/*.exe

    # - name: Move artifacts
    #   id: vars
    #   shell: pwsh
    #   run: |
    #     $sha = (git rev-parse --short HEAD)
    #     md -Name ./dist/artifacts -Force
    #     Compress-Archive -Path ./dist/win-unpacked -DestinationPath ./dist/artifacts/win-unpacked-x64.zip
    #     Copy-Item ./dist/*.exe -Destination ./dist/artifacts/
    #     $file = Get-ChildItem -Path ./dist/artifacts/ -Filter "*.exe" | select-object -first 1
    #     $newName = "$($file.BaseName).$($sha)$($file.Extension)"
    #     Rename-Item -Path $file.FullName -NewName $newName
    #     echo "::set-output name=fileName::$($newName)"
