name: "Test Build"
on:
  push:
    branches:
      - main
    tags:
      - 'v2-nightly*'

env:
  RUST_BACKTRACE: 1
  CARGO_INCREMENTAL: 0 # This is set to 0 by the https://github.com/Swatinem/rust-cache
  CARGO_PROFILE_DEV_DEBUG: 0 # This would add unnecessary bloat to the target folder, decreasing cache efficiency.

jobs:
  tauri-build:
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Get Current Date
        if: matrix.platform == 'windows-latest'
        run: echo "CURRENT_DATE=$(Get-Date -Format "yyyy-MM-dd")" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Build
        env:
          GH_TOKEN: ${{ secrets.GH_DOWNLOAD_TOKEN }}
        run: |
          $release_name=(gh api -H "Accept: application/vnd.github+json" /repos/cangzhang/league-client-tencent/releases/latest --jq ".name")
          gh release download "$release_name" -R cangzhang/league-client-tencent -p "*exe" -D src-tauri/ --clobber && echo "ðŸ³ Downloaded LeagueClient $release_name"
          npm i -g pnpm && pnpm install --no-frozen-lockfile && pnpm tauri build
          New-Item .\src-tauri\target\release\msi -ItemType Directory -Force
          Move-Item -Force -Path src-tauri/LeagueClient.exe -Destination src-tauri/target/release/
          Move-Item -Force -Path src-tauri/target/release/bundle/msi/*.msi -Destination "src-tauri/target/release/msi/ChampR_$env:GITHUB_REF_NAME.msi"

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          path: |
            src-tauri/target/release/msi/*
            src-tauri/target/release/*.exe

      - name: Create Nightly Release
        uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/v2-nightly')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          prerelease: true
          artifacts: "src-tauri/target/release/msi/*"
          body: >
            [FAQ](https://github.com/cangzhang/champ-r/wiki/FAQ) 
            <br/>
